Exercicio 03 - pronto para revisão
LucasAlexander13/helpper-sprint-1 pull request #5
Opened 2021-10-30 01:36 UTC by LucasAlexander13

2021-10-30 01:37 UTC, LucasAlexander13 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 03](https://trello.com/c/PWer27c7/50-exerc%C3%ADcio-03)

2021-11-01 18:47 UTC, LucasAlexander13 commented
Códigos prontos para nova revisão

2021-11-04 22:14 UTC, alanrocha-helpper requested changes

2021-11-04 22:14 UTC, alanrocha-helpper commented on Exercicio-03/funcional.ts
> +    const menor_valor: number = nova_lista.reduce((valor, auxiliar) => Math.min(valor, auxiliar));
com o Math.min e Math.max é só você utilizar com decomposição na passagem do parametro, que a função já te retorna o dado que vc deseja

No caso `Math.min(...nova_lista)`  &&  `Math.max(...nova_lista)`

2021-11-04 22:14 UTC, alanrocha-helpper commented on Exercicio-03/funcional.ts
> +    const somatorio = (valor: number, auxiliar: number) => { return valor + auxiliar };
quando vc usa arrow function, e logo depois da seta já tem um return, não precisa abrir chaves, pode usar direto a instrução `const somatorio = (valor: number, auxiliar: number) => valor + auxiliar ;`

2021-11-06 15:01 UTC, alanrocha-helpper approved these changes

2021-11-06 15:04 UTC, merged