Exercicio 02 - pronto para revisão
LucasAlexander13/helpper-sprint-1 pull request #6
Opened 2021-10-30 12:45 UTC by LucasAlexander13

2021-10-30 12:47 UTC, LucasAlexander13 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 02](https://trello.com/c/exhXPiRV/49-exerc%C3%ADcio-02)

2021-10-30 20:36 UTC, alanrocha-helpper requested changes

2021-10-30 20:36 UTC, alanrocha-helpper commented on Exercicio-02/funcional.ts
> +    return lista.find((pessoa: Pessoa) => pessoa.id === id).bio;
ficou bom a lógica, mas se não encontrar uma pessoa com o id passado, vai estourar um erro de bio não existe em undefined;

você pode usar o operador null safety, ou o operador OU `||` e retornar o resultado da pesquisa ou uma mensagem de erro.

2021-10-30 20:36 UTC, alanrocha-helpper commented on Exercicio-02/funcional.ts
> +function retornarNome(id: number): string {
mesmo caso da função anterior

2021-10-30 20:36 UTC, alanrocha-helpper commented on Exercicio-02/funcional.ts
> +function alterarInfo(id:number, tipo: string, info: string): boolean {
Alguns pontos. 

Primeiro, você não precisa de um if pra verificar qual a propriedade vai ser alterada, você pode acessar a chave do objeto dessa forma `objeto[chave]`.

Segundo, na sua função, você procura a pessoa pelo id, quando encontra, somente substitui o valor no objeto encontrado, e não coloca de volta na lista esse cara alterado.

Sugiro que ao entrar na função, utilize na lista um findIndex, e depois reorganize a logica da função. 

Quanto a tipos e nomes de variaveis,. Estão ok.

2021-10-30 20:36 UTC, alanrocha-helpper commented on Exercicio-02/imperativo.ts
> +// declaração da variável
Não é por que você está fazendo imperativo que você não precisa usar tipagem quando possivel, como fez na funcional com a interface Pessoa.

2021-11-01 14:34 UTC, LucasAlexander13 commented
Correções realizadas, código pronto para nova revisão

2021-11-01 15:11 UTC, alanrocha-helpper requested changes

2021-11-01 15:11 UTC, alanrocha-helpper commented on Exercicio-02/funcional.ts
> +    return lista.find((pessoa: Pessoa) => pessoa.id === id)?.bio as string;
Você não precisa forçar o retorno como string, dado que a lista já é tipada, e a propriedade já é uma string

2021-11-01 15:11 UTC, alanrocha-helpper commented on Exercicio-02/funcional.ts
> +    return lista.find((pessoa: Pessoa) => pessoa.id === id)[tipo] = info;
aqui você alterou só o objeto, mas na lista, continua o mesmo valor, precisa mudar o valor que está na lista. um findIndex seria mais adequando, e depois refatorar a função;

2021-11-01 15:11 UTC, alanrocha-helpper commented on Exercicio-02/imperativo.ts
> +    for(let i: number = 0; i < lista.length; i++) {
Cara, evitar utilizar variaveis com nomes como i, x, y, z, btn, aux. Sempre o mais descritivo possivel. nesse caso, um index cairia bem. Vale para o restante das outras funções

2021-11-01 19:39 UTC, LucasAlexander13 commented
Refatoração da função alterarInfo, usando findIndex para encontrar o id

2021-11-04 21:13 UTC, alanrocha-helpper approved these changes

2021-11-05 12:53 UTC, merged