Hotfix ex01 - Pronto para revisão
LucasAlexander13/helpper-sprint-1 pull request #7
Opened 2021-10-30 20:42 UTC by LucasAlexander13

Correções do Exercício 01:
- Laço continuo para teste das palavras;
- Demonstração do funcionamento no console.log;

2021-10-30 20:46 UTC, LucasAlexander13 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 01](https://trello.com/c/fhLsZce1/48-exerc%C3%ADcio-01)

2021-10-30 21:53 UTC, alanrocha-helpper requested changes

2021-10-30 21:53 UTC, alanrocha-helpper commented on Exercicio-01/numVogais.ts
> +console.log(numVogais(`Lucas possui ${numVogais("Lucas")} vogais`))
Cara, eu acho que o que você quis fazer aqui foi 
console.log(Lucas possui ${numVogais("Lucas")} vogais)

acerta esse aí, e na linha de baixo também, que já aprovo

2021-10-31 01:37 UTC, LucasAlexander13 commented on Exercicio-01/numVogais.ts
> +console.log(numVogais(`Lucas possui ${numVogais("Lucas")} vogais`))
Fiz as atualizações no último commit, segue o link:
[https://github.com/LucasAlexander13/helpper-sprint-1/commit/858809c5ae36cb9364dfbfaf57a68ec4cd7736a5](url)

2021-10-31 11:45 UTC, merged